name: Continuous integration for serverless coders!

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Determine the canonical owner
        run: |
          whoami
